version: '2'
services:
  client:
    container_name: client
    restart: always
    build:
      context: .
      dockerfile: client.Dockerfile
    ports:
      - '4200:80'
    links:
      - app

  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - '3000:3000'
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
