version: '2'
services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
    ports:
      - '4200:80'

  app:
    container_name: app
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    ports:
      - '3000:3000'
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
